### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by xiaoparrot** [Macr0phag3/email_hack#1]
我用好几台服务器测试，全是显示time out 连接超时，qq，google邮箱都是，为啥呀大佬？

**Comment by Macr0phag3** [comment]
我这里是没问题的。等待一会试试看？

**Comment by Macr0phag3** [comment]
![image](https://user-images.githubusercontent.com/20874963/48926881-a31c7f80-ef0c-11e8-9a82-0d5ce1f87eed.png)
@xiaoparrot 我刚跑了还是 ok 的。不过用的是163邮箱。至于 qq 邮箱，我这边显示 Ip frequency limited. 估计是其他人用这个出口 ip 搞事情了吧。
![image](https://user-images.githubusercontent.com/20874963/48926901-d52de180-ef0c-11e8-95d2-5823223d2cce.png)

**Comment by xiaoparrot** [comment]
gmail也不行，看来只能玩163了，啊啊啊啊
