### ISSUE TITLE
550 Domain may not exist or DNS check failed

### ISSUE THREAD

**Issue by NickYan7** [Macr0phag3/email_hack#8]
测试时遇到了这个问题，意思是伪造的域不存在吗？nslookup 查询后 freebuf.com 是软错误啊。

![Screenshot 2020-07-28 下午4 21 29](https://user-images.githubusercontent.com/27906343/88638806-90e5e200-d0ee-11ea-9766-8da1e100d6b7.jpg)
![Screenshot 2020-07-28 下午4 21 09](https://user-images.githubusercontent.com/27906343/88638815-94796900-d0ee-11ea-9b1b-21a05c39d3e8.jpg)

**Comment by Macr0phag3** [comment]
fb 的 spf 设置了 softfail，即 ~all，所以伪造不会成功。我个人感觉，收件方在查到 softfail 的时候应该都会选择直接拒绝。
@NickYan7

**Comment by NickYan7** [comment]
> fb 的 spf 设置了 softfail，即 ~all，所以伪造不会成功。我个人感觉，收件方在查到 softfail 的时候应该都会选择直接拒绝。
> @NickYan7

谢谢！可是看您的博客，huawei.com 也是 softfail，为什么可以利用成功呢？
@Macr0phag3

**Comment by Macr0phag3** [comment]
遇到 softfail 的时候，得看 qq 怎么处理了。我当时伪造华为 hr 的发件人，发 qq 邮箱是测试成功了。但是现在我没法测试，因为华为的策略已经改为 -all 了，甚至上了 DMARC...所以我现在只能给你说一下我的推测：我当时测试的时候，qq 邮箱没这么严格，遇到 softfail 不拒绝，现在变得严格了，遇到 softfail 直接拒绝。

**遇到 softfail 的时候，要看收件方怎么处理这个情况，有可能直接拒绝，有可能通过，这个说不好。**

**Comment by NickYan7** [comment]
@Macr0phag3 
明白了，感谢！
