### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Rsv002** [Macr0phag3/email_hack#9]
dns.resolver.NoResolverConfiguration: cannot open /etc/resolv.conf

**Comment by Macr0phag3** [comment]
@Rsv002 

这个应该是 dns 库的报错

请提供一下你的 python 版本和操作系统信息，仅凭这么一句话没人能帮你解决

**Comment by Macr0phag3** [comment]
auto: 无回复，关闭 issue，若还有问题可再开
